p8105_hw2_jj3564
================
2025-10-01

# Problem 0

This homework uses GitHub, R Projects, and R Markdown for
reproducibility. All data files are stored in the `data/` sub directory,
and relative paths are used.

# Problem 1

## data cleaning first

``` r
## load data
pols_df = read_csv("data/fivethirtyeight_datasets/pols-month.csv")

## clean data
pols_cleaned = pols_df |> 
  separate('mon', into = c("year", "month", "day"), sep = "-", convert = TRUE) |> 
  mutate(
      month = month.name[month],
      president = case_when(
      prez_dem == 1 ~ "dem",
      prez_gop == 1 ~ "gop",
      TRUE ~ NA_character_
    )
  ) |> 
  select(-prez_gop,-prez_dem, -day) |> 
  select (year, month, president, everything())
  
pols_cleaned
```

    ## # A tibble: 822 × 9
    ##     year month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <int> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January   dem            23      51     253      23      45     198
    ##  2  1947 February  dem            23      51     253      23      45     198
    ##  3  1947 March     dem            23      51     253      23      45     198
    ##  4  1947 April     dem            23      51     253      23      45     198
    ##  5  1947 May       dem            23      51     253      23      45     198
    ##  6  1947 June      dem            23      51     253      23      45     198
    ##  7  1947 July      dem            23      51     253      23      45     198
    ##  8  1947 August    dem            23      51     253      23      45     198
    ##  9  1947 September dem            23      51     253      23      45     198
    ## 10  1947 October   dem            23      51     253      23      45     198
    ## # ℹ 812 more rows

The pols-month.csv dataset contained monthly political control data,
including presidential party affiliation (prez_gop/prez_dem) and the
distribution of governorships and congressional seats, starting from
1947.

## Clean snp.csv data

``` r
## load data
snp_df = read_csv("data/fivethirtyeight_datasets/snp.csv")

## clean data
snp_cleaned = snp_df |> 
  separate(date, into = c("month_num", "day", "year_short"), sep = "/", convert = TRUE)  |> 

  mutate(
    year = case_when(
      year_short <= 49 ~ year_short + 2000,
      year_short >= 50 ~ year_short + 1900,
    ),
    month = month.name[month_num]
  )  |>  
  select(year, month, snp_value = close) |> 
    # arrange by year and month
  arrange(year, month)

snp_cleaned
```

    ## # A tibble: 787 × 3
    ##     year month    snp_value
    ##    <dbl> <chr>        <dbl>
    ##  1  1950 April         18.0
    ##  2  1950 August        18.4
    ##  3  1950 December      20.4
    ##  4  1950 February      17.2
    ##  5  1950 January       17.0
    ##  6  1950 July          17.8
    ##  7  1950 June          17.7
    ##  8  1950 March         17.3
    ##  9  1950 May           18.8
    ## 10  1950 November      19.5
    ## # ℹ 777 more rows

### Clean `unemployment.csv`

This dataset is in wide format, with months as columns. We pivot it into
long format and ensure the month variable matches the same names as
before

``` r
## load data
unemployment_df = read_csv("data/fivethirtyeight_datasets/unemployment.csv")

## tidy data
unemployment_cleaned = unemployment_df |> 
  rename(year = Year) |> 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
mutate(
    month = month.name[match(month, month.abb)]
) |> 
select(year, month, unemployment) |> 
arrange(year, month)

unemployment_cleaned
```

    ## # A tibble: 816 × 3
    ##     year month    unemployment
    ##    <dbl> <chr>           <dbl>
    ##  1  1948 April             3.9
    ##  2  1948 August            3.9
    ##  3  1948 December          4  
    ##  4  1948 February          3.8
    ##  5  1948 January           3.4
    ##  6  1948 July              3.6
    ##  7  1948 June              3.6
    ##  8  1948 March             4  
    ##  9  1948 May               3.5
    ## 10  1948 November          3.8
    ## # ℹ 806 more rows

### Merge datasets

We merge `pols` with `snp`, then merge unemployment.

``` r
mergesum_df = pols_cleaned |> 
  left_join(snp_cleaned, by = c("year", "month")) |> 
  left_join(unemployment_cleaned, by = c("year", "month"))

mergesum_df
```

    ## # A tibble: 822 × 11
    ##     year month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January   dem            23      51     253      23      45     198
    ##  2  1947 February  dem            23      51     253      23      45     198
    ##  3  1947 March     dem            23      51     253      23      45     198
    ##  4  1947 April     dem            23      51     253      23      45     198
    ##  5  1947 May       dem            23      51     253      23      45     198
    ##  6  1947 June      dem            23      51     253      23      45     198
    ##  7  1947 July      dem            23      51     253      23      45     198
    ##  8  1947 August    dem            23      51     253      23      45     198
    ##  9  1947 September dem            23      51     253      23      45     198
    ## 10  1947 October   dem            23      51     253      23      45     198
    ## # ℹ 812 more rows
    ## # ℹ 2 more variables: snp_value <dbl>, unemployment <dbl>

``` r
final_dim = dim(mergesum_df)
final_years = range(mergesum_df$year)
final_names = names(mergesum_df)

mergesum_df
```

    ## # A tibble: 822 × 11
    ##     year month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January   dem            23      51     253      23      45     198
    ##  2  1947 February  dem            23      51     253      23      45     198
    ##  3  1947 March     dem            23      51     253      23      45     198
    ##  4  1947 April     dem            23      51     253      23      45     198
    ##  5  1947 May       dem            23      51     253      23      45     198
    ##  6  1947 June      dem            23      51     253      23      45     198
    ##  7  1947 July      dem            23      51     253      23      45     198
    ##  8  1947 August    dem            23      51     253      23      45     198
    ##  9  1947 September dem            23      51     253      23      45     198
    ## 10  1947 October   dem            23      51     253      23      45     198
    ## # ℹ 812 more rows
    ## # ℹ 2 more variables: snp_value <dbl>, unemployment <dbl>

**Summary**: The `pols` dataset contains information about political
party control. The `snp` dataset contains S&P stock market closing
values. The `unemp` dataset contains unemployment percentages. After
merging, we have observations, spanning to . Key variables: `year`,
`month`, `president`, `close` (S&P index), and `unemployment`.

# Problem 2: Trash Wheel Data

### Clean Mr. Trash Wheel

``` r
mr_trash <- read_excel("data/202509 Trash Wheel Collection Data.xlsx",  sheet = "Mr. Trash Wheel",
  range = cell_cols("A:N")) %>%
janitor::clean_names() %>%
filter(!is.na(dumpster)) %>%
mutate(
    sports_balls = as.integer(round(sports_balls, 0)),
    year = as.numeric(year),    
    wheel = "Mr. Trash Wheel")
```

### Clean Professor Trash Wheel

``` r
prof_trash <- read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) %>%
janitor::clean_names() %>%
filter(!is.na(dumpster)) %>%
mutate(
    year = as.numeric(year),   
    wheel = "Professor Trash Wheel"
  )
```

### Clean Gwynnda

``` r
  gwynnda_df <- read_excel(
  "data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynns Falls Trash Wheel"
) |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    year = as.numeric(year),     
    wheel = "Gwynns Falls Trash Wheel"
  )
trash_all <- bind_rows(mr_trash, prof_trash, gwynnda_df)
```

### Summary statistics

``` r
n_obs <- nrow(trash_all)
total_prof_weight <- sum(filter(trash_all, wheel == "Professor")$weight_tons, na.rm = TRUE)
gwynnda_cigs_jun22 <- trash_all %>% filter(wheel == "Gwynnda", month == 6, year == 2022) %>%
summarize(total = sum(cigarette_butts, na.rm = TRUE)) %>% pull(total)


n_obs; total_prof_weight; gwynnda_cigs_jun22
```

    ## [1] 1188

    ## [1] 0

    ## [1] 0

**Summary**: The combined dataset has 1188 observations. Key variables
include dumpster ID, collection date, trash weight, and item counts.
Professor Trash Wheel collected 0 tons of trash in total. Gwynnda
collected 0 cigarette butts in June 2022.

# Problem 3: Zillow Rent Data

## Wrangling the datasets

We start by importing both the Zillow Observed Rent Index (ZORI) data
and the ZIP code reference file. Then we reshape ZORI into tidy format
and create useful date variables.

``` r
# File paths
zori_path <- "data/zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv"
zip_path  <- "data/zillow_data/Zip Codes.csv"

# Tidy ZORI dataset
zori_data <- read_csv(zori_path) |> 
  pivot_longer(
    cols = matches("^20"),   # select columns that look like years
    names_to = "date",
    values_to = "rent_index"
  ) |> 
  mutate(
    date = ymd(date),
    year = year(date),
    month_num = month(date)
  )

# Clean ZIP code dataset
zip_data <- read_csv(zip_path) |> 
   janitor::clean_names() 
```

## Merge the datasets

Next, we join the rent index data with neighborhood-level ZIP
information.

``` r
zillow_data <- zori_data |> 
  left_join(zip_data, by = c("RegionName" = "zip_code")) |> 
  arrange(RegionName, date)
```

## Dataset description

We summarize the size of the final dataset and highlight how many unique
ZIP codes and neighborhoods are included.

``` r
n_total <- nrow(zillow_data)

n_zipcodes <- n_distinct(zillow_data$RegionName)

n_hoods <- n_distinct(zillow_data$neighborhood)

list(
  total_observations = n_total,
  distinct_zipcodes = n_zipcodes,
  distinct_neighborhoods = n_hoods
)
```

    ## $total_observations
    ## [1] 17516
    ## 
    ## $distinct_zipcodes
    ## [1] 149
    ## 
    ## $distinct_neighborhoods
    ## [1] 43

``` r
names(zillow_data)
```

    ##  [1] "RegionID"     "SizeRank"     "RegionName"   "RegionType"   "StateName"   
    ##  [6] "State"        "City"         "Metro"        "CountyName"   "date"        
    ## [11] "rent_index"   "year"         "month_num"    "county"       "state_fips"  
    ## [16] "county_code"  "county_fips"  "file_date"    "neighborhood"

``` r
str(zillow_data$month_num)
```

    ##  num [1:17516] 1 2 3 4 5 6 7 8 9 10 ...

``` r
str(zillow_data$year)
```

    ##  num [1:17516] 2015 2015 2015 2015 2015 ...

``` r
str(zillow_data$date)
```

    ##  Date[1:17516], format: "2015-01-31" "2015-02-28" "2015-03-31" "2015-04-30" "2015-05-31" ...

The tidy dataset is structured as follows:

- The dataset contains **17516 total observations**.  
- There are **149 unique ZIP codes** represented.  
- These ZIP codes span **43 different neighborhoods** across NYC.

## ZIP codes not present in ZORI

We identify which ZIP codes are in the geographic reference file but
missing in the Zillow rent dataset.

``` r
missing_zipcodes <- setdiff(zip_data$zip_code, unique(zori_data$RegionName))
```

There are 171 ZIP codes absent from the Zillow rent index. The first
five are shown below:

``` r
zip_data |>
  filter(zip_code %in% missing_zipcodes) |>
  select(zip_code, county, neighborhood) |>
  head(5) |>
  knitr::kable(caption = "First 5 ZIP Codes Missing from ZORI")
```

| zip_code | county | neighborhood               |
|---------:|:-------|:---------------------------|
|    10464 | Bronx  | Southeast Bronx            |
|    10474 | Bronx  | Hunts Point and Mott Haven |
|    10475 | Bronx  | Northeast Bronx            |
|    10499 | Bronx  | NA                         |
|    10550 | Bronx  | NA                         |

First 5 ZIP Codes Missing from ZORI

Possible explanations include:

1.  **Low listing counts**: ZIP codes with very few rental listings
    might not meet Zillow’s threshold for index calculation.
2.  **Specialized land use**: ZIP codes dominated by parks, campuses, or
    commercial zones may lack sufficient market housing.
3.  **Incomplete data**: Some areas might not have reliable or
    consistent data over time.

## Rental price changes during COVID

We now compare rent levels between January 2020 and January 2021.

``` r
price_changes_tmp <- zillow_data |> 
  filter(date %in% c("2020-01-31", "2021-01-31")) |> 
 
 select(-year) |> 
  pivot_wider(
    names_from = date, 
    values_from = rent_index,
    names_prefix = "price_"
  ) |> 


  mutate(price_change = `price_2021-01-31` - `price_2020-01-31`) |> 
  arrange(desc(price_change)) |> 
  slice(1:10)
```

The table below shows the 10 ZIP codes with the sharpest declines.

``` r
price_changes_tmp |>
  select(
    `ZIP Code` = RegionName,
    Borough = county, 
    Neighborhood = neighborhood,
    `Rent Jan 2020` = `price_2020-01-31`,
    `Rent Jan 2021` = `price_2021-01-31`,
    `Drop in Rent ($)` =
  ) |>
  knitr::kable(
    digits = 2,
    caption = "Top 10 NYC ZIP Codes with Largest Rent Drop (Jan 2020 vs Jan 2021)"
  )
```

| ZIP Code | Borough  | Neighborhood              | Rent Jan 2020 | Rent Jan 2021 |
|---------:|:---------|:--------------------------|--------------:|--------------:|
|    11432 | Queens   | Jamaica                   |       1894.91 |       1996.11 |
|    10467 | Bronx    | Bronx Park and Fordham    |       1649.56 |       1744.51 |
|    10458 | Bronx    | Bronx Park and Fordham    |       1375.98 |       1420.38 |
|    10463 | Bronx    | Kingsbridge and Riverdale |       2169.42 |       2205.92 |
|    10463 | New York | Kingsbridge and Riverdale |       2169.42 |       2205.92 |
|    10462 | Bronx    | Southeast Bronx           |       1681.77 |       1706.89 |
|    11229 | Kings    | Southern Brooklyn         |       1782.82 |       1797.04 |
|    11220 | Kings    | Sunset Park               |       2134.51 |       2139.88 |
|    10457 | Bronx    | Central Bronx             |       1850.37 |       1848.52 |
|    11109 | Queens   | NA                        |       3291.92 |       3288.71 |

Top 10 NYC ZIP Codes with Largest Rent Drop (Jan 2020 vs Jan 2021)

**Interpretation**: The biggest rental declines occurred in Manhattan,
particularly in business-heavy areas such as Downtown and Midtown. These
trends reflect the pandemic-driven outmigration and drop in demand for
high-cost rentals in dense neighborhoods that rely on in-office work.
